theme: jekyll-theme-minimal
encoding: UTF-8
title: ASP.NET Core Web API Course
email: alhabish@gmail.com
#repository: "kalhabish/kalhabish.github.io"
repository: "alhabish"
author: خالد الغامدي
lang: ar-SA
locale: ar-SA
dir: rtl
description: "تعلم برمجة الـ REST APIS بإستخدام تقنية ASP.NET Core"

# User/Organization page
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://alhabish.github.io" 
# or url: "https://alhabish.com" if you have a custom domain name

# Project page
baseurl: "/aspnetcorewebapi-course" # the subpath of your site, e.g. /blog
url: "https://alhabish.github.io/aspnetcorewebapi-course" # the base hostname & protocol for your site, e.g. http://example.com

# According to
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
#baseurl: "/aspnetcorewebapi-course"
#url: "https://alhabish.github.io"

twitter_username: alhabish
github_username:  alhabish
linkedin_account: "khalidalghamidi"
google_analytics: UA-106571814-2
show_downloads: false

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false

